
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;
import 'GameObj.sol';
import 'AddUnit.sol';
import 'MilitaryUnit.sol';


contract BaseStation is GameObj, AddUnit {
    address[] private unitList;
    constructor() public {
        tvm.accept();
        defencePoins = 8;
        baseAddress = address(msg.pubkey());
    }

    function addUnit(address unit) public override{
        tvm.accept();
        unitList.push(unit);
    }

    function death(address dest) public virtual override{
        if(GameObj.isDead()){
            for (address unit: unitList) {
                MilitaryUnit(unit).sendAll(dest);
            }
            sendAll(dest);
        }
    }

    function removeUnit(address unit, address dest) public override {
        //require(msg.pubkey() == tvm.pubkey() || MilitaryUnit(unit).getDefencePoins() == 0);
        tvm.accept();
        bool check = false;
        for (uint i = 0; i < unitList.length-1; i++){
            if (unitList[i] == unit) {
                check = true;
            }
            if (check) {
                unitList[i] = unitList[i+1];
            }
        }
        if (check||unitList[unitList.length-1]==unit) {
            unitList.pop();
            MilitaryUnit arch = MilitaryUnit(unit);
            arch.sendAll(dest);
        }
    }

    function getUnitList() public returns(address[]){
        return unitList;
    }
}
